# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a59ed4e6f26cb744585023cb9231efbc573439a44c2e2732a18eb2a67bc283fdea9819a07b9c47d55c091f8209291892cdbb05011ca77d0ba44a4ae6d5e31f

test:
  secret_key_base: 05977a01e9090da9c56b3791a68305fda98994f3085c64a7e9ba3ae95528b863355510e4b55b87a38e0bc5fec9df41caddab258494072bc857601fe37d388482

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
